### ISSUE TITLE
Hist_plot.py not working 

### ISSUE THREAD

**Issue by kcl58759** [dfguan/purge_dups#109]
Hi, This is the error I get when I try to use hist_plot.py command

Traceback (most recent call last):
  File "/apps/eb/Purge_dups/1.2.5-foss-2019b-Python-3.8.2/scripts/hist_plot.py", line 4, in <module>
    import matplotlib as mpl
ModuleNotFoundError: No module named 'matplotlib'

**Comment by LandiMi2** [comment]
@dfguan I am getting a different error message.

Traceback (most recent call last):
  File "/data01/mlandi/software/purge_dups/scripts/hist_plot.py", line 82, in <module>
    mk_plot(hists, cutoffs, opts.title, opts.xmin, opts.xmax, opts.ymin, opts.ymax, opts.out_fn) 
  File "/data01/mlandi/software/purge_dups/scripts/hist_plot.py", line 56, in mk_plot
    plt.xlim([0, max(cutoffs)*1.5])
ValueError: max() arg is an empty sequence

Please assist.

**Comment by LeoVincenzi** [comment]
@LandiMi2 did you get any answers from the authors? 
I'm currently facing the same issue.
