### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Malabady** [dfguan/purge_dups#16]
Hi,

I keep getting a segmentation fault when running the "pbcstat" on the paf.gz file, which is a 10G file. See the following:

16:57:12    $ ~/software/purge_dups/bin/pbcstat reads2contigs.paf.gz
Program starts
[M::aa_pb] collecting positions from paf file
[M::aa_pb] calculating coverage for each base on genome
[M::aa_pb] select supported regions
Segmentation fault (core dumped)

My reads are Pacbio reads (Sequel II reads). The machine has 120Gb of RAM. Does it need more? 

Thanks

**Comment by dfguan** [comment]
Hi Malababy,  your paf.gz file is big, which seems a little bit unreal for paf files, Could you please make sure you use "minimap2 -xccs -t12 $ref $fastq > A.paf" to produce a paf file? I have a feeling that you might have added "-a" to  minimap2 which output sam instead of paf. If everything is ok, I will check my code. Best, Dengfeng.

**Comment by Malabady** [comment]
Hi,
Thanks for the reply. Here is my minimap2 command:
minimap2 -t 25  -x map-pb Spu.contigs.mmi all.subreads.min1kb.fastq | gzip -c - > reads2contigs.paf.gz

**Comment by Malabady** [comment]
I was a bit concerned about the paf file, but i dont see what is wrong in the command.

**Comment by dfguan** [comment]
Could you send me the first 100 lines in your paf file (dfguan9@gmail.com)? Also could you try minimap2 with -xccs?

**Comment by dfguan** [comment]
How many reads do you have?

**Comment by Malabady** [comment]
I just sent you the top 100 lines. I have about 22 million reads.

**Comment by dfguan** [comment]
Hi Mala, thanks, it seems good. I have updated the source files, you could use git pull to get the newest code, and remake the executable files, rerun pbcstat and send the log to me, so I can debug. Thanks again. Dengfeng.

**Comment by Malabady** [comment]
Hi,
Here is the log of the run using the updated code:
20:36:56    $ ~/software/purge_dups/bin/pbcstat reads2contigs.paf.gz
Program starts
[M::aa_pb] collecting positions from paf file
[M::aa_pb] calculating coverage for each base on genome
[M::aa_pb] print coverage histogram for the contigs
Segmentation fault (core dumped)

Thanks

**Comment by Malabady** [comment]
I want to note that even with this segmentation fault, it still produces a PB.stat file. But I don't know if this stat file is complete and correct. In fact I produced the coverage plot, see the attached file.
![PB cov](https://user-images.githubusercontent.com/9359920/68820437-3b999b80-0659-11ea-8044-04128a2b2439.png)

**Comment by Malabady** [comment]
Hi,

I compiled the tool on a Mac computer and rerun the analysis, the core dump problem went away. It seems that it had something to do with our computer clusters, not the tool itself. 

Could you please elaborate on the following step? 
Step 4. Merge hap.fa and $hap_asm and redo the above steps to get a decent haplotig set.
I understand that hap.fa is produced by step three. But what is $hap_asm? where is it coming from? is it the primary diploid assembly? By merging, do you mean just concatenate both files? And do mean redoing all steps from the beginning? 

Thanks

**Comment by dfguan** [comment]
Hi Magdy, 


Hap_asm is the allelic contigs, if you just have the primary contig set, you can skip this. If you run falcon-unzip, there will be primary contig set and alternative contig set which is the $hap_asm. Merging means concatenation. And by redoing all the steps, I mean doing the same thing on the merged assembly from step 1 to 3. 

Technically there should still be a bug, I think. And I need to find and resolve it. I hope you could help. I changed pbcstat.c to output mapping information and have sent to you through gmail, could you please recompile purge_dups and run pbcstat.c and send me the output file? Here is the command "pbcstat $PAF 2>pbcstat.log", please send me the pbcstat.log file, that would be helpful. 

Best, 

Dengfeng

**Comment by plnspineda** [comment]
Hi Dengfeng,

I am having the same problem both in my personal computer and our work computer cluster. But I am getting the same problem at `purge_dups` function.

This is my run which gives the following error:

`/bin/purge_dups -T cutoffs -c PB.base.cov asm.self.paf.gz > dups.bed 2> purge_dups.log`
`Segmentation fault (core dumped)`

What could be the reason for this error?

I am also having a problem with getting the plot with the following error:

```
(minimap2) p**@d**nux:~/path/$ python3 purge_dups/scripts/hist_plot.py PB.stat PB.coverage.png
Traceback (most recent call last):
  File "~path/purge_dups/scripts/hist_plot.py", line 82, in <module>
    mk_plot(hists, cutoffs, opts.title, opts.xmin, opts.xmax, opts.ymin, opts.ymax, opts.out_fn) 
  File "~path/purge_dups/scripts/hist_plot.py", line 56, in mk_plot
    plt.xlim([0, max(cutoffs)*1.5])
ValueError: max() arg is an empty sequence
```
cutoffs value is the following:

5	47	77	93	155	279

I also tried adding -x 2 and -X 400, but still getting the same problem with python3.7 and python3.10.

I'd greatly appreciate your help. Thank you!
