### ISSUE TITLE
Error in Process 4 with cal_cov()

### ISSUE THREAD

**Issue by grendon** [dfguan/purge_dups#71]
Hi,

I am trying to run the pipeline rather than running the steps manually. 
I see results in the seq folder; files ending in *hap.fa and purged.fa
But I also see an error in the log file as shown below.  
Could you please tell me what could be the problem and how to fix it? 
Thanks.

<pre>
Process Process-4:
Traceback (most recent call last):
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/apps2/software/Python/3.7.2-IGB-gcc-8.2.0/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
TypeError: cal_cov() missing 2 required positional arguments: 'spid' and 'ispurged'

</pre>

**Comment by dfguan** [comment]
Hi, are you using the latest purge_dups pipeline? I think I have already fixed this bug. Best, Dengfeng.

**Comment by dfguan** [comment]
Hi, are you using the latest purge_dups pipeline? I think I have already fixed this bug. Best, Dengfeng.

**Comment by dfguan** [comment]
Hi, are you using the latest purge_dups pipeline? I think I have already fixed this bug. Best, Dengfeng.
